### ISSUE TITLE
Fn::GetAtt for ClientSecret not supported

### ISSUE THREAD

**Issue by carlsborg** [awsdocs/aws-cloudformation-user-guide#148]
Hello, 

This page:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html

seems to have some missing information, which is in the github pages: 

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-cognito-userpoolclient.md

Questions:
Why is there a discrepancy?
Can we assume the github version is the source of truth?
How often are the website /latest docs updated? 

Thanks!

**Comment by carlsborg** [comment]
Cloudformation returns "ClientSecret attribute not supported at this time, please use the CLI or Console to retrieve this value"

The github doc is incorrect then.

**Comment by ckesser** [comment]
Hi @carlsborg,
Thank you for raising this question. I apologize for the confusion (and the delay in responding to this!). Because we make updates to the CloudFormation documentation almost daily, the AWS documentation source files on GitHub can temporarily become out of sync. I'm happy to say that we recently synced up our docs on September 21, and we plan to publish on a regular basis moving forward to reduce the lag time. 
Closing out this issue.
