### ISSUE TITLE
Adding schedulingStrategy in cloudformation 

### ISSUE THREAD

**Issue by yrsurya** [awsdocs/aws-cloudformation-user-guide#158]
Is it possible to use schedulingStrategy feature in cloudformation template - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html#service_scheduler

**Comment by cmmeyer** [comment]
Hi, @yrsurya  --  the daemon scheduler hasn't been exposed via CloudFormation yet, which is why it's not in the docs.  Keep an eye on the https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
page -- it should be coming in a future coverage drop.

Feel free to open a thread in the [AWS Forums](https://forums.aws.amazon.com) if you'd like to dive deeper on this.

**Comment by ckesser** [comment]
Support for this feature has since been added: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-schedulingstrategy

Thanks for raising this issue, @yrsurya. Closing.
