### ISSUE TITLE
Unable to read stack status from DescribeStackSet() Cloudformation template

### ISSUE THREAD

**Issue by krithikas01-88** [awsdocs/aws-cloudformation-user-guide#482]
Hi all,

I'm trying to get the description of the created Cloud formation template stack deployed by using the API given in go sdk: 

func describeStackSet(svc cloudformationiface.CloudFormationAPI) {
	//id := "arn:aws:cloudformation:us-east-2:690826095747:stack/test-stack-1/8da7a6a0-de2d-11e9-8d21-0659c08a3f80" / stack name as string * = "test-with-sg"

	input := &cloudformation.DescribeStackSetInput{StackSetName: aws.String(
		"test-with-sg")}
	resp, err := svc.DescribeStackSet(input)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			fmt.Println(awsErr.Code() + " " + awsErr.Message())
		}
	} else {
		fmt.Println("printing deployment status: " + *resp.StackSet.Status)
	}

Any idea why its trying to read a non existing stack. 
"StackSetNotFoundException StackSet test-with-sg not found"
same error persists with using either ARN or Name. 

The stack did exist in the right region (here us-east-2). with the same name. /arn.

**Comment by krithikas01-88** [comment]
can somone help analyze why certain API are deprecated and not yet removed from AWS API ?

**Comment by PatMyron** [comment]
[`describe-stack-set`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-stack-set.html) is not deprecated, I'd try double checking that it is calling the correct regional endpoint with the correct StackSet name with the correct credentials for the correct AWS account. One possible issue when trying the ARN above is that ARN is a [stack ARN instead of a stackSet ARN](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscloudformation.html#awscloudformation-resources-for-iam-policies)

If you're still encountering issues calling [`DescribeStackSet` through the Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#CloudFormation.DescribeStackSet), I'd recommend reaching out to AWS support or on the AWS Forums for further assistance
