### ISSUE TITLE
AWS::DocDB::DBCluster property VPCSecurityGroupIds is an unsupported property

### ISSUE THREAD

**Issue by Sulster** [awsdocs/aws-cloudformation-user-guide#644]
When trying to reference a security group id Cloudformation will Roll Back with the following:

> Property validation failure: [Encountered unsupported properties in {/}: [VPCSecurityGroupIds]]

The Cluster part of the Template looks like:
```
DocumentDBCluster: 
    Type: AWS::DocDB::DBCluster
    Properties: 
      VPCSecurityGroupIds: 
        - !GetAtt DocumentDBSecurityGroup.GroupId
      BackupRetentionPeriod : 5
      DBClusterIdentifier : !Ref DBClusterName
      DBSubnetGroupName : !Ref DocumentDBSubnetGroup
```

I've tried various ways of referencing the security group however I get the exact same error each time. Dropping the VPCSecurityGroupIds property entirely allows the entire Template to be created successfully.

**Comment by PatMyron** [comment]
Just a capitalization difference, should be [`VpcSecurityGroupIds`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-vpcsecuritygroupids) instead of `VPCSecurityGroupIds`

Recommend the [CloudFormation Linter](https://github.com/aws-cloudformation/cfn-python-lint/) and the [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint) for autocompletion:

<img width="470" alt="Screen Shot 2020-04-13 at 1 04 03 PM" src="https://user-images.githubusercontent.com/7014355/79156200-4df23f80-7d87-11ea-8bbd-534359f9187a.png">
