### ISSUE TITLE
Periodic updates introducing regressions

### ISSUE THREAD

**Issue by castaples** [awsdocs/aws-cloudformation-user-guide#699]
The commit to the master branch a5ef3d027dafc15518186d3a84c5d4f984213fc0 has cause a regression to an [accepted PR](https://github.com/awsdocs/aws-cloudformation-user-guide/pull/691) I submitted a week ago to the following page https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-servicecatalog-cloudformationproduct.md

This has lead to the documentation once again being incorrect and may also have affected other changes. Committing directly to the master branch is generally bad practice when using git and doesn't follow your own contributing guide, https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/CONTRIBUTING.md

**Comment by castaples** [comment]
@ckesser are you aware of this issue and are you able to correct this?

**Comment by rachfop** [comment]
Hello @castaples sorry for the late reply. Your commit that was accepted is showing up here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-cloudformationproduct.html

The GitHub documentation can be a few days behind the official AWS docs. Because of that, we do a general merge to allow time for the docs to catch up. I apologize that your changes didn't show up correctly but we are always listening to our customer feedback to see where we can improve the most. This is an area that we are working on. Thank you for your suggestion.
